@startuml
skinparam monochrome true
skinparam shadowing false
skinparam packageStyle rectangle
skinparam roundcorner 5

title EDA Broker 

' --- ELEMENTOS ---

rectangle "Initiating Event\n(InterfaceCliente)" as UI <<Initiating Event>>

node "Message Broker (RabbitMQ)" as Broker {
    queue "Canal: SolicitarPedido" as Chan1 <<Event Channel>>
    queue "Canal: PedidoConfirmado" as Chan2 <<Event Channel>>
}

' Seus Gerenciadores com os componentes internos reais
rectangle "Event Processor\n(GerenciadorPedido)" as P_Ped {
    component [Service]
    component [RepositoryPedido]
}

rectangle "Processing Event\n(PedidoConfirmado)" as E1 <<Processing Event>>

rectangle "Event Processor\n(GerenciadorRestaurante)" as P_Rest {
    component [ServiceRestaurante]
    component [RepositoryProduto]
}

rectangle "Event Processor\n(GerenciadorEntregador)" as P_Ent {
    component [ServiceEntregador]
    component [RepositoryEntregador]
}

rectangle "Event Processor\n(GerenciadorLocalizacao)" as P_Loc {
    component [Service]
    component [Repository]
}

' --- FLUXO ---

UI -down-> Chan1 
Chan1 -down-> P_Ped 
P_Ped -down-> E1  
E1 -up-> Chan2 

Chan2 -down-> P_Rest 
Chan2 -down-> P_Ent 
Chan2 -down-> P_Loc 

@enduml